### ISSUE TITLE
`hand_tracking_toolkit` only required when working with HOT3D 

### ISSUE THREAD

**Issue by nv-nguyen** [thodan/bop_toolkit#134]
@MedericFourmy it would be great to make `hand_tracking_toolkit` only required when working HOT3D  in [this line](https://github.com/thodan/bop_toolkit/blob/master/bop_toolkit_lib/misc.py#L18). Many users are working on BOP-classic which does not require this package. It is also worthy noting that this package requires many external libraries (please in attached images).

Besides, it would be great to add instruction of installing `hand_tracking_toolkit` in README.md

<img width="1237" alt="Screenshot 2024-08-24 at 12 17 00" src="https://github.com/user-attachments/assets/9a92c959-b9a5-4135-8214-ce7413161f42">

**Comment by MedericFourmy** [comment]
Have you tried to install all dependencies in a python 3.7 environment? I created a fresh conda environment this morning on my machine (Ubuntu 22.04) and could do it.
We are indeed using only a subpart of the hand_tracking_toolkit while inheriting all its dependencies.

The issue is that at the moment, since merging https://github.com/thodan/bop_toolkit/pull/130 hand_tracking_toolkit _is_ a mandatory dependency (being imported in `eval_calc_error.py` and `misc.py`) which is why it was included in the `requirements.txt`. A PR should address this issue too.
