### ISSUE TITLE
Could I use this dataset( PBR images) for object detection?

### ISSUE THREAD

**Issue by ShougangShen** [thodan/bop_toolkit#31]
hello, @thodan . Could I use the PBR dataset for object detection? I noticed you provide the bbox GT(ground truth), but the format isn't compatible with Faster RCNN, YOLO, etc. 
And I noticed that the  PBR dataset GT are different from other datasets(LM, LM-O, etc.). How can I convert PBR GT format to LM format?

**Comment by thodan** [comment]
Hi, the format of the [PBR dataset](https://thodan.github.io/objectsynth/) is very similar to the BOP format. The main difference is that the GT annotations are saved in the YAML instead of the JSON format (the conversion should be straightforward). You can use the PBR dataset to train object detection methods, but will need to convert it to the format of YOLO etc. by yourself (use items "obj_bb" and "obj_bb_visib" from the GT files to get the 2D bounding box of the full object and of only its visible part respectively).
