### ISSUE TITLE
How to generate mask images

### ISSUE THREAD

**Issue by eagleeye05** [thodan/bop_toolkit#53]
I have generated my own dataset in BOP format.
And I am using 'bop_toolkit/scripts/calc_gt_masks.py ' to generate masks and visib_mask images.
However, our generated mask images are totally black. I am wondering whether there are some parameters we should config? (I have config the dataset path)

Thanks!
@thodan

**Comment by thodan** [comment]
Hello, are your 3D models in mm? Try to also play with the delta tolerance (set to 15 mm by default).

**Comment by ing-THOMAS** [comment]
Hello @thodan,

I'm a beginner in this field.
Actually i'm tring to use this "calc_gt_masks.py" too. And the same probleme occurred probably because my 3D models are in m. Could you tell me how can i solve it? Can i simply change the 3D models into mm? I'm always confused about simply changing 3D models scales because i generated depth, rgb, scene_camera.json, scene_gt.json all theses datas by "DLR-RM/BlenderProc", using the 3D models in m. If i change the 3D models into mm, will anything be wrong? ex: translation or something? 

Or i can just leave the 3D models in m and then how can i use this script?

Thank you in advance!

**Comment by 3Proto** [comment]
@eagleeye05 how did you generate your own dataset? I really can't get my head round it.
